FROM ubuntu:24.04

#Install necessary packages
RUN DEBIAN_FRONTEND=noninteractive \
	apt-get update \
	&& apt-get install -y wget bzip2 make unzip cppcheck clang-format git

#Create non-root user named "ubuntu" that belongs in root group for GitHub actions permissions

RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo \
	-u 1001 ubuntu
USER ubuntu
WORKDIR /home/ubuntu


